const express = require('express')
const cors = require("cors")
const Auth = require("../controllers/AuthController")
const City = require('../controllers/CityController')
const Theatre = require("../controllers/TheatreController")
const Screen = require("../controllers/ScreenController")
const Seat = require("../controllers/SeatController")
const ShowSeat = require("../controllers/ShowSeatController")
const Show = require("../controllers/ShowController")
const Booking = require('../controllers/BookingController')
const Payment = require('../controllers/PaymentController')
const MovieSearch = require("../controllers/MovieSearchController")
module.exports = function (app){
    app.use(express.json())
    app.use(express.urlencoded({extended:true}))
    app.use("/api/Auth",Auth)
    app.use("/api/City",City)
    app.use("/api/Theatre",Theatre)
    app.use("/api/Screen",Screen)
    app.use("/api/Seat",Seat)
    app.use("/api/ShowSeat",ShowSeat)
    app.use("/api/Shows",Show)
    app.use("/api/Booking",Booking)
    app.use("/api/Payment",Payment)
    app.use("/api/movies",MovieSearch)
}